"""Constants for the Firewalla Local integration."""

from __future__ import annotations

import logging
from datetime import timedelta
from typing import Final

DOMAIN: Final = "firewalla_local"
LOGGER: Final = logging.getLogger(__name__)
MANUFACTURER: Final = "Firewalla"

# Entity state attributes
ATTR_PURPOSE: Final = "purpose"
ATTR_RULE_PURPOSE: Final = "purpose"
ATTR_RULE_ID: Final = "rule_id"
ATTR_RULE_TEMPLATE_TARGET: Final = "target"
ATTR_RULE_TARGET_TYPE: Final = "target_type"
ATTR_RULE_TAG_REFS: Final = "tag_refs"
ATTR_RULE_NOTES: Final = "notes"
ATTR_RULE_IS_PAUSED: Final = "is_paused"
ATTR_RULE_PAUSE_UNTIL: Final = "pause_until"
ATTR_SYSTEM_BOOT_COMPLETE: Final = "boot_complete"
ATTR_SYSTEM_CPU_LOAD_5M: Final = "cpu_load_5m"
ATTR_SYSTEM_CLOUD_CONNECTED: Final = "cloud_connected"
ATTR_SYSTEM_DDNS: Final = "ddns"
ATTR_SYSTEM_DISK_USAGE_PERCENT_BY_MOUNT: Final = "disk_usage_percent_by_mount"
ATTR_SYSTEM_FIRMWARE_RELEASE_TYPE: Final = "firmware_release_type"
ATTR_SYSTEM_MEMORY_FREE_MB: Final = "memory_free_mb"
ATTR_SYSTEM_MEMORY_USAGE_PERCENT: Final = "memory_usage_percent"
ATTR_SYSTEM_WAN_IP: Final = "wan_ip"
ATTR_SYSTEM_WAN_IPS: Final = "wan_ips"
ATTR_SPEED_TEST_DOWNLOAD_MBYTES: Final = "download_megabytes"
ATTR_SPEED_TEST_ISP: Final = "isp"
ATTR_SPEED_TEST_JITTER: Final = "jitter"
ATTR_SPEED_TEST_LATENCY: Final = "latency"
ATTR_SPEED_TEST_MANUAL: Final = "manual"
ATTR_SPEED_TEST_PACKET_LOSS: Final = "packet_loss"
ATTR_SPEED_TEST_PUBLIC_IP: Final = "public_ip"
ATTR_SPEED_TEST_SERVER_COUNTRY: Final = "server_country"
ATTR_SPEED_TEST_SERVER_HOST: Final = "server_host"
ATTR_SPEED_TEST_SERVER_ID: Final = "server_id"
ATTR_SPEED_TEST_SERVER_LOCATION: Final = "server_location"
ATTR_SPEED_TEST_SERVER_SPONSOR: Final = "server_sponsor"
ATTR_SPEED_TEST_SUCCESS: Final = "success"
ATTR_SPEED_TEST_TESTED_AT: Final = "tested_at"
ATTR_SPEED_TEST_UPLOAD: Final = "upload_speed"
ATTR_SPEED_TEST_UPLOAD_MBYTES: Final = "upload_megabytes"
ATTR_SPEED_TEST_VENDOR: Final = "vendor"

# Service input fields
SERVICE_FIELD_CONFIG_ENTRY_ID: Final = "config_entry_id"
SERVICE_FIELD_CONFIG_ENTRY_NAME: Final = "config_entry_name"
SERVICE_FIELD_RULE_DURATION: Final = "duration"
SERVICE_FIELD_RULE_RESUME_AT: Final = "resume_at"
SERVICE_FIELD_RULE_TARGET: Final = "rule_target"

# Config entry data and options keys
CONF_AID: Final = "aid"
CONF_EID: Final = "eid"
CONF_GID: Final = "gid"
CONF_HOST: Final = "host"
CONF_LICENSE: Final = "license"
CONF_LOCAL_IP: Final = "local_ip"
CONF_QR_JSON: Final = "qr_json"
CONF_SELECTED_RULE_IDS: Final = "selected_rule_ids"
CONF_SELECTED_RULE_TEMPLATES: Final = "selected_rule_templates"
CONF_SYMMETRIC_KEY: Final = "symmetric_key"

APP_API_BASE: Final = "https://firewalla.encipher.io/app/api/v2"
APP_GROUP_ENDPOINT_CANDIDATES: Final = (
    "/ept/group/me",
    "/ept/groups/me",
)
FIREWALLA_PROTOCOL_CLIENT_ID: Final = "com.rottiesoft.circle"
FIREWALLA_PROTOCOL_CLIENT_KEY: Final = "fbb05afa-9145-41f1-8076-9de8be56f104"
FIREWALLA_PROTOCOL_CLIENT_VERSION: Final = "1.51.84"

DEFAULT_UPDATE_INTERVAL: Final = timedelta(minutes=3)
DEFAULT_GROUP_POLL_ATTEMPTS: Final = 10
DEFAULT_GROUP_POLL_INTERVAL: Final = 3.0
DEFAULT_INIT_TARGET: Final = "0.0.0.0"
DEFAULT_FIREWALLA_HOST: Final = "fire.walla"
DEFAULT_PAIRING_DEVICE_NAME: Final = "Home Assistant"
DEFAULT_BOX_NAME: Final = "Firewalla"
ENTITY_SUFFIX_SENSOR: Final = "sensor"
ENTITY_SUFFIX_SWITCH: Final = "switch"
PLATFORM_SENSOR: Final = "sensor"
PLATFORM_SWITCH: Final = "switch"
RULE_ACTION_ALLOW: Final = "allow"
RULE_ACTION_BLOCK: Final = "block"
RULE_PURPOSE_FAMILY: Final = "family"
RULE_TARGET_TAG: Final = "TAG"
RULE_TARGET_TYPE_CATEGORY: Final = "category"
RULE_TARGET_TYPE_DNS: Final = "dns"
RULE_TARGET_TYPE_IP: Final = "ip"
RULE_TARGET_TYPE_MAC: Final = "mac"
RULE_TARGET_TYPE_NETWORK: Final = "network"
RULE_TARGET_TYPE_REMOTE_PORT: Final = "remotePort"
CONFIG_ERROR_CANNOT_CONNECT: Final = "cannot_connect"
CONFIG_ERROR_INVALID_HOST: Final = "invalid_host"
CONFIG_ERROR_INVALID_QR: Final = "invalid_qr"
CONFIG_ERROR_WRONG_ACCOUNT: Final = "wrong_account"
SERVICE_GET_RUNTIME_INVENTORY: Final = "get_runtime_inventory"
SERVICE_PAUSE_RULE: Final = "pause_rule"
SERVICE_RESUME_RULE: Final = "resume_rule"
SYSTEM_STATUS_STATE_AVAILABLE: Final = "available"
SYSTEM_STATUS_STATE_UNAVAILABLE: Final = "unavailable"
TRANS_KEY_EXCEPTION_CONFIG_ENTRY_NAME_AMBIGUOUS: Final = "config_entry_name_ambiguous"
TRANS_KEY_EXCEPTION_CONFIG_ENTRY_NAME_NOT_FOUND: Final = "config_entry_name_not_found"
TRANS_KEY_EXCEPTION_CONFIG_ENTRY_NOT_FOUND: Final = "config_entry_not_found"
TRANS_KEY_EXCEPTION_CONFIG_ENTRY_NOT_LOADED: Final = "config_entry_not_loaded"
TRANS_KEY_EXCEPTION_INVALID_DURATION: Final = "invalid_duration"
TRANS_KEY_EXCEPTION_MULTIPLE_ENTRIES_LOADED: Final = "multiple_entries_loaded"
TRANS_KEY_EXCEPTION_PAUSE_RULE_TIMING_CONFLICT: Final = "pause_rule_timing_conflict"
TRANS_KEY_EXCEPTION_RESUME_AT_IN_PAST: Final = "resume_at_in_past"
TRANS_KEY_EXCEPTION_RULE_TARGET_NOT_FOUND: Final = "rule_target_not_found"
TRANS_KEY_EXCEPTION_WRONG_INTEGRATION_ENTRY: Final = "wrong_integration_entry"
TRANS_KEY_ENTITY_SENSOR_LATEST_SPEED_TEST_DOWNLOAD: Final = "latest_speed_test_download"
TRANS_KEY_ENTITY_SENSOR_SYSTEM_STATUS: Final = "system_status"
TRANS_KEY_ENTITY_SWITCH_ALLOW_RULE: Final = "allow_rule"
TRANS_KEY_ENTITY_SWITCH_BLOCK_RULE: Final = "block_rule"
TRANS_KEY_PURPOSE_SYSTEM_BOOT_STATUS: Final = "purpose_system_boot_status"
TRANS_KEY_PURPOSE_RULE_SWITCH: Final = "purpose_rule_control"
TRANS_PLACEHOLDER_DURATION: Final = "duration"
TRANS_PLACEHOLDER_RULE_NAME: Final = "rule_name"
TRANS_PLACEHOLDER_RULE_TARGET: Final = "rule_target"
